# Generated by Django 3.0.7 on 2024-08-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
    ]
