# Generated by Django 3.0.7 on 2024-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240729_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
