# Generated by Django 3.0.7 on 2024-08-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20240806_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_style',
        ),
        migrations.RemoveField(
            model_name='car',
            name='no_of_owners',
        ),
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_no',
        ),
    ]
